import React, { useEffect, useState } from 'react';
import Header from '../../components/header';
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from '../../config/session';
import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import ResponsiveImage from '../../components/ResponsiveImage'

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
  const user = req.session.user;
  const props = {};
  if (user) {
    props.user = req.session.user;
    props.isLoggedIn = true;
  } else {
    props.isLoggedIn = false;
  }
  return { props };
  },
  sessionOptions
  );

  export default function CharPortrait(props) {

    const saveFormData = async (event) => {
        event.preventDefault();
        const charName = sessionStorage.getItem('charName')
        const formData = new FormData(event.target);
        const picURL = formData.get('picURL');
        try {
                const res = await fetch("/api/char-update", {
                    method: "POST",
                    headers: {
                      "content-type": "application/json"
                    },
                    body: JSON.stringify({ id: character._id, charData: {picURL: picURL}}),
                  });
                  if (res.status === 200) window.location.href = '/';
            } catch(error) {
            console.log('Error: ', error)
        }
      }

    return (
        <div className={styles.container}>
        <Head>
          <title>Provide your Character&apos;s Portrait</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
  
        <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />
  
        <main className={styles.main}>
            <h2>Provide the portrait URL for your character. You may choose to leave the form blank if you wish.</h2>
            <form onSubmit={saveFormData}>
            <label htmlFor="picURL">Portrait URL: </label>
            <input type="text" id="picURL" name="picURL"/>
            </form>
        </main>
  
        <footer className={styles.footer}>
          <a
            href="https://fallout.fandom.com/wiki/Nuka-Cola"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span className={styles.logo}>
            <ResponsiveImage imageUrl="/PoweredByNuka.png" altText="Powered by Nuka Cola" />
            </span>
          </a>
        </footer>
      </div>
    )
  }