import Head from "next/head";
import ResponsiveImage from '../../components/ResponsiveImage'
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../../config/session";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import useLogout from "../../hooks/useLogout";
import { useState } from "react";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function CharacterRace(props) {
  const router = useRouter();
  const logout = useLogout();
  const [selectedRace, setSelectedRace] = useState('');

  const saveFormData = (event) => {
    event.preventDefault();
    const formData = new FormData(event.target);
    const selectedRace = formData.get('item');
    const charName = formData.get('characterName')
    sessionStorage.setItem('selectedRace', selectedRace);
    sessionStorage.setItem('charName', charName);
    if (selectedRace == 'Human' || selectedRace == 'Ghoul' || selectedRace == 'Synth' || selectedRace == 'Mole Miner' || selectedRace == 'Robot') {
      sessionStorage.setItem('size', 'Medium');
    } else {
      sessionStorage.setItem('size', 'Large');
    }
    window.location.href = '/character-creator/background';
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Select Your Name & Race</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
      <h2>Pick Your Race:</h2>
      <form onSubmit={saveFormData}>
      <label htmlFor="characterName">Name: </label>
      <input type="text" id="characterName" name="characterName" required /><br /><br />
        <input type="radio" id="item1" name="item" value={'Human'} required/>
        <label htmlFor="item1">Human</label><br />
        <input type="radio" id="item2" name="item" value={'Ghoul'} required/>
        <label htmlFor="item1">Ghoul</label><br />
        <input type="radio" id="item3" name="item" value={'Synth'} required/>
        <label htmlFor="item1">Synth</label><br />
        <input type="radio" id="item4" name="item" value={'Eastern Super Mutant'} required/>
        <label htmlFor="item1">Eastern Super Mutant</label><br />
        <input type="radio" id="item5" name="item" value={'Western Super Mutant'} required/>
        <label htmlFor="item1">Western Super Mutant</label><br />
        <input type="radio" id="item6" name="item" value={'Mole Miner'} required/>
        <label htmlFor="item1">Mole Miner</label><br />
        <input type="radio" id="item7" name="item" value={'Robot'} required/>
        <label htmlFor="item1">Robot</label><br />
        <input type="radio" id="item8" name="item" value={'Intelligent Deathclaw'} required/>
        <label htmlFor="item1">Intelligent Deathclaw</label><br />
        <input type="submit" value={'Submit'}/>
      </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://fallout.fandom.com/wiki/Nuka-Cola"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
          <ResponsiveImage imageUrl="/PoweredByNuka.png" altText="Powered by Nuka Cola" />
          </span>
        </a>
      </footer>
    </div>
  );
}
// 