import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import { useState } from "react";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function CharacterRace(props) {
  const router = useRouter();
  const logout = useLogout();
  const [selectedRace, setSelectedRace] = useState('');

  const saveFormData = (event) => {
    event.preventDefault();
    const formData = new FormData(event.target);
    const selectedRace = formData.get('item');
    sessionStorage.setItem('selectedRace', selectedRace);
    window.location.href = '/background';
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Select Your Race</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
      <h2>Pick Your Race:</h2>
      <form onSubmit={saveFormData}>
        <input type="radio" id="item1" name="item" value={'Human'} />
        <label htmlFor="item1">Human</label><br />
        <input type="radio" id="item2" name="item" value={'Ghoul'} />
        <label htmlFor="item1">Ghoul</label><br />
        <input type="radio" id="item3" name="item" value={'Synth'} />
        <label htmlFor="item1">Synth</label><br />
        <input type="radio" id="item4" name="item" value={'Eastern Super Mutant'} />
        <label htmlFor="item1">Eastern Super Mutant</label><br />
        <input type="radio" id="item5" name="item" value={'Western Super Mutant'} />
        <label htmlFor="item1">Western Super Mutant</label><br />
        <input type="radio" id="item6" name="item" value={'Mole Miner'} />
        <label htmlFor="item1">Mole Miner</label><br />
        <input type="radio" id="item7" name="item" value={'Robot'} />
        <label htmlFor="item1">Robot</label><br />
        <input type="radio" id="item8" name="item" value={'Intelligent Deathclaw'} />
        <label htmlFor="item1">Intelligent Deathclaw</label><br />
        <input type="submit" value={'Submit'}/>
      </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
